// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

const sumEvenFibonacci = (numberLimit) => {
    let fib = [0, 1]
    let fibEven = []

    for (i = 2; (fib[i - 2] + fib[i - 1]) < numberLimit; i++) {
        fib[i] = fib[i - 2] + fib[i - 1]
        if (fib[i] % 2 === 0) {
            fibEven.push(fib[i])
        }
    }
    console.log(`Fibonacci Sqeuence: ${fib}`)
    console.log(`Even Fibonacci Sqeuence: ${fibEven}`)

    const sumEven = fibEven.reduce((acc, current) => acc + current)
    console.log(`Sum of Even Numbers in Fibonacci Sqeuence: ${sumEven}`)

}

sumEvenFibonacci(4000000)

